### PR TITLE
update loadFry function

### PR DESCRIPTION
**Pull request by DongzeHE**
Hi @mikelove,

In alevin-fry 0.4.1, the `meta_info.json` is called `quant.json` as discussed at https://github.com/COMBINE-lab/alevin-fry/issues/22#issuecomment-885222997 .

### CODE REVIEW

**Comment by mikelove** [comment]
Thanks, pushing now to Bioc

**Comment by mikelove** [comment]
Oops with this pull I get a test error when running `R CMD check`

```
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  > test_check("fishpond")
  ══ Skipped tests ═══════════════════════════════════════════════════════════════
  • empty test (5)

  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error (test_loadFry.R:13:3): Reading in Alevin-fry USA count matrix works ───
  Error: argument "txt" is missing, with no default
  Backtrace:
      █
   1. └─fishpond::loadFry(fry.dir) test_loadFry.R:13:2
   2.   └─jsonlite::fromJSON(file = qfile)

  [ FAIL 1 | WARN 0 | SKIP 5 | PASS 18 ]
  Error: Test failures
  Execution halted
```

**Comment by mikelove** [comment]
I've removed the loadFry test temporarily, could you take a look and when you get `R CMD check` passing re-PR?

**Comment by DongzeHE** [comment]
I realized that the error is caused by the discrepancy between `rjson` and `JSONlite` packages! It can be easily solved by changing line 55 from `meta_info <- fromJSON(file = qfile)` to `meta_info <- fromJSON(txt = qfile)`. Sorry about the mistake, I will re-PR.

**Pull request merged**
